package com.mafei.stacksaga.common.enums;

public enum RedisEvents {
    NONE,
    NEW_SERVER_UP,
    GET_TRANSACTION_REQUEST,
    GET_TRANSACTION_RESPONSE,
    GET_TRANSACTION_TRACE_REQUEST,
    GET_TRANSACTION_TRACE_RESPONSE,
    RESTART_INSTANCE_REQUEST,
    RESTART_INSTANCE_RESPONSE,
    SEARCH_TRANSACTIONS_REQUEST,
    SEARCH_TRANSACTIONS_RESPONSE,
    GET_AGGREGATOR_REQUEST,//get aggregator list for font
    GET_AGGREGATOR_RESPONSE,
}
